### ISSUE TITLE
Hebbot stores news when it is mentioned

### ISSUE THREAD

**Issue by thibaultamartin** [haecker-felix/hebbot#1]
The bot listens to the reporting room. When someone sends a message _starting with_ the bot's display name or MatrixID, the bot captures:
* The MatrixID of the person reporting it
* The display name of the person reporting
* The text of message where it was mentioned, stripped from the mention and leading space (be it spaces, tabs or line breaks)
* A link to this message

It stores this `news` structure in its internal `store`, with the flag `pending approval`.

If the bot stored the message, it answers with:

> Thanks `displayName of the reporter`, I stored your update

If it didn't success at storing the message, it answers with:

> Something went wrong `displayName of the reporter`, I couldn't store your update

It also sends a message in the admin room saying:

> `@room` I couldn't store this message: `link to the message`

In the following example, the bot named TWIG stores the message:
> TWIG: Dark mode is now supported!

In the following example, the bot named TWIG does not store the message:
> I wonder if dark mode support is TWIG worthy

In the following ewample, the bot named TWIG does not store the message:
> TWIGable or not TWIGable? I don't know

**Comment by haecker-felix** [comment]
Implemented :+1:
