### ISSUE TITLE
Editor can approve an update to be added in the report

### ISSUE THREAD

**Issue by thibaultamartin** [haecker-felix/hebbot#4]
Everyone can react to a message posted in the reporting room with any emoji.
When the reporters react with the ⭕ emoji, the bot does nothing.

When one of the editor reacts with the ⭕ emoji, the bot updates the `news` in its store to remove the `pending approval` flag and flag it as `approved`

People can un-react with ⭕, in which case the bot must verify the number of editors who have a ⭕ reaction on the `news`. If that numbers hits 0, the bot removes the `approved` flag and sets it back to `pending approval`.

**Comment by haecker-felix** [comment]
Implemented :heavy_check_mark:
