### ISSUE TITLE
Editor can sort a news in one or several categories

### ISSUE THREAD

**Issue by thibaultamartin** [haecker-felix/hebbot#5]
The bot has a configurable map of emojis. This structure maps a given emoji with a `section`.

Everyone can react to a `news` posted in the reporting room with an emoji bound to a section, in which case the bot does nothing.

When one of the editors reacts to a `news` with an emoji bound to a section, the bot flags the `news` as belonging to a given section.

If one of the editors reacts with several emojis corresponding to different sections, the bot flags the `news` as belonging to all matching sections.

**Comment by haecker-felix** [comment]
Implemented :heavy_check_mark:
