### ISSUE TITLE
Editor can issue a report as a markdown file

### ISSUE THREAD

**Issue by thibaultamartin** [haecker-felix/hebbot#7]
When receiving the command `!report file` in the administrator room, the bot tries to read the template. If it cannot find the template, it answers with:

> I could not find or read the template

If it finds the template, it reads it and replaces the `{{report}}` string with the generated report. It then answers with the generated report in the template.

The report is created as follows:

1. The bot lists all sections that have at least one approved news
2. For each section, the bot adds:
    1. `## {{section title matching the emoji}}`
    2. `[{{displayName of the reporter}}](https://matrix.to/#/{{matrixID of the reporter}}) reports that`
    3. `> {{message of thenews}}`
    4. a line break
3. Then the bot adds `## TO SORT`
4. For each approved news that doesn't have a section, the bot adds:
    1. `[{{displayName of the reporter}}](https://matrix.to/#/{{matrixID of the reporter}}) reports that`
    2. `> {{message of thenews}}`
    3. `{{link to the message}}`
    4. a line break
5. For each unapproved news, the bot adds:
    1. `[{{displayName of the reporter}}](https://matrix.to/#/{{matrixID of the reporter}}) reports that`
    2. `> {{message of thenews}}`
    3. `{{link to the message}}`
    4. a line break

The bot then issues the report and sends it as a markdown file in the admin room

**Comment by haecker-felix** [comment]
Implemented :heavy_check_mark:
