### ISSUE TITLE
images: Support High DPI screenshots

### ISSUE THREAD

**Issue by sophie-h** [haecker-felix/hebbot#71]
- Mark images as high DPI in report room
- Generate HTML that scales the images correctly

My idea was to tag screenshots with both, the notice ⭕ and something like 2️⃣ for 2x scaling. Would require enhancing the data structure for `News.images`. Would probably make sense to make it a struct at this point?

**Comment by haecker-felix** [comment]
> Generate HTML

And that's already an problem. Hebbot should generate plain markdown, no HTML. 

Additionally, it makes me wonder if this is something that should be controlled by hebbot at all. The too large images would be fixed by a few lines of CSS on the TWIG homepage, for example.

**Comment by sophie-h** [comment]
> The too large images would be fixed by a few lines of CSS on the TWIG homepage, for example.

How would TWIG know that an image is High DPI?

**Comment by haecker-felix** [comment]
Has TWIG to know that? Just limit image height inside the quotes to 600px via CSS for example

**Comment by sophie-h** [comment]
My idea was to display screenshots not larger than they would appear on the user's desktop. That would require all of that.

But I think in practice it will be fine with the CSS fix you merged.
