### ISSUE TITLE
Editor can speak in the name of the bot

### ISSUE THREAD

**Issue by thibaultamartin** [haecker-felix/hebbot#9]
When receiving a command starting with `!say` in the admin room, the bot posts a message in the reporting room, containing everything that follows the actual command.

Example, if in the admin room someone issues says

> !say Entries are now closed, thanks for having submitted them

The bot will say in the reporting room

> Entries are now closed, thanks for having submitted them

**Comment by haecker-felix** [comment]
Implemented :heavy_check_mark:
